/**
 *  Ações do usuário 
 */
const USER_UPDATE = "USER_UPDATE";
const USER_RESET = "USER_RESET";

/**
 * Ações do usuário form
 */

const UPDATE_PROGRESS = "UPDATE_PROGRESS";
const SET_NAME = "SET_NAME";
const SET_URLCODE = "SET_URLCODE";
const SET_PAYMENT = "SET_PAYMENT";
const SET_COMPLEMENTARY = "SET_COMPLEMENTARY";
const SET_PHONE = "SET_PHONE";
const SET_CITY = "SET_CITY";
const SET_MEDICAL = "SET_MEDICAL";
const SET_AVAILABLE_MEDICAL = "SET_AVAILABLEMEDICAL";
const SET_COORDINATES = "SET_COORDINATES";
const SET_MANUAL_GEOLOCATION = "SET_MANUALGEOLOCATION";
const RESET_FORM = "RESET_FORM";

/**
 * Configurações do form
 */

const SET_SEARCH_MEDICAL = "SET_SEARCHMEDICAL";
const SET_ALLOW_GEOLOCATION = "SET_ALLOWGEOLOCATION";
const SET_SUPPORT_GEOLOCATION = "SET_SUPPORTGEOLOCATION";

/**
 * Atualizações de configurações da página
 */

const USER_SETTINGS_PER_PAGE_UPDATE = "USER_SETTINGS_PER_PAGE_UPDATE";

/**
 *  Atualizações das listas
 */
const USERS_LIST_UPDATE = "USERS_LIST_UPDATE";
const USERS_LIST_GET = "USERS_LIST_GET";

/**
 * Opções de informacoes de pagina
 */
const SET_PAGE_TITLE = "SET_PAGE_TITLE"
const SET_PAGE_SUBTITLE = "SET_PAGE_SUBTITLE"

export {
    USER_UPDATE,
    USER_RESET,
    USERS_LIST_UPDATE,
    USERS_LIST_GET,
    USER_SETTINGS_PER_PAGE_UPDATE,
    UPDATE_PROGRESS,
    SET_NAME,
    SET_URLCODE,
    SET_PAYMENT,
    SET_COMPLEMENTARY,
    SET_PHONE,
    SET_CITY,
    SET_MEDICAL,
    SET_AVAILABLE_MEDICAL,
    SET_COORDINATES,
    SET_MANUAL_GEOLOCATION,
    RESET_FORM,
    SET_SEARCH_MEDICAL,
    SET_ALLOW_GEOLOCATION,
    SET_SUPPORT_GEOLOCATION,
    SET_PAGE_TITLE,
    SET_PAGE_SUBTITLE
}