/**
 *  Ações do usuário 
 */
const USER_SET_ID = "USER_SET_ID";
const USER_SET_NAME = "USER_SET_NAME";
const USER_SET_BIRTHDAY = "USER_SET_BIRTHDAY";
const USER_SET_PHONE = "USER_SET_PHONE";
const USER_SET_EMAIL = "USER_SET_EMAIL";
const USER_SET_AVATAR = "USER_SET_AVATAR";
const USER_SET_POSTALCODE = "USER_SET_POSTALCODE";
const USER_SET_ADDRESS = "USER_SET_ADDRESS";
const USER_SET_NUMBER = "USER_SET_NUMBER";
const USER_SET_COUNTY = "USER_SET_COUNTY";
const USER_RESET = "USER_RESET";
const USER_SET_PRICE = "USER_SET_PRICE";

/**
 * Ações do usuário form
 */

const SET_NETWORK_STATUS_CONNECTION = "SET_NETWORK_STATUS_CONNECTION";

const UPDATE_PROGRESS = "UPDATE_PROGRESS";
const SET_NAME = "SET_NAME";
const SET_URLCODE = "SET_URLCODE";
const SET_PAYMENT = "SET_PAYMENT";
const SET_COMPLEMENTARY = "SET_COMPLEMENTARY";
const SET_PHONE = "SET_PHONE";
const SET_CITY = "SET_CITY";
const SET_CATEGORY = "SET_CATEGORY";
const SET_MEDICAL = "SET_MEDICAL";
const SET_AVAILABLE_MEDICAL = "SET_AVAILABLEMEDICAL";
const SET_COORDINATES = "SET_COORDINATES";
const SET_MANUAL_GEOLOCATION = "SET_MANUALGEOLOCATION";
const RESET_FORM = "RESET_FORM";

/**
 * Configurações do form
 */

const SET_SEARCH_MEDICAL = "SET_SEARCHMEDICAL";
const SET_ALLOW_GEOLOCATION = "SET_ALLOWGEOLOCATION";
const SET_SUPPORT_GEOLOCATION = "SET_SUPPORTGEOLOCATION";

/**
 * Atualizações de configurações da página
 */

const USER_SETTINGS_PER_PAGE_UPDATE = "USER_SETTINGS_PER_PAGE_UPDATE";

/**
 *  Atualizações das listas
 */
const USERS_LIST_UPDATE = "USERS_LIST_UPDATE";
const USERS_LIST_GET = "USERS_LIST_GET";

/**
 * Opções de informacoes de pagina
 */
const SET_PAGE_TITLE = "SET_PAGE_TITLE"
const SET_PAGE_SUBTITLE = "SET_PAGE_SUBTITLE"

export {
    USER_SET_ID,
    USER_SET_NAME,
    USER_SET_BIRTHDAY,
    USER_SET_EMAIL,
    USER_SET_AVATAR,
    USER_SET_PHONE,
    USER_SET_POSTALCODE,
    USER_SET_ADDRESS,
    USER_RESET,
    USER_SET_NUMBER,
    USER_SET_COUNTY,
    USERS_LIST_UPDATE,
    USERS_LIST_GET,
    USER_SETTINGS_PER_PAGE_UPDATE,
    UPDATE_PROGRESS,
    USER_SET_PRICE,
    SET_NAME,
    SET_URLCODE,
    SET_PAYMENT,
    SET_COMPLEMENTARY,
    SET_PHONE,
    SET_CITY,
    SET_CATEGORY,
    SET_MEDICAL,
    SET_AVAILABLE_MEDICAL,
    SET_COORDINATES,
    SET_MANUAL_GEOLOCATION,
    RESET_FORM,
    SET_SEARCH_MEDICAL,
    SET_ALLOW_GEOLOCATION,
    SET_SUPPORT_GEOLOCATION,
    SET_PAGE_TITLE,
    SET_PAGE_SUBTITLE,
    SET_NETWORK_STATUS_CONNECTION
}